// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/api/order/order.proto

package order

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SingleOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Products      []*ProductData         `protobuf:"bytes,3,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleOrder) Reset() {
	*x = SingleOrder{}
	mi := &file_pkg_api_order_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleOrder) ProtoMessage() {}

func (x *SingleOrder) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_order_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleOrder.ProtoReflect.Descriptor instead.
func (*SingleOrder) Descriptor() ([]byte, []int) {
	return file_pkg_api_order_order_proto_rawDescGZIP(), []int{0}
}

func (x *SingleOrder) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SingleOrder) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SingleOrder) GetProducts() []*ProductData {
	if x != nil {
		return x.Products
	}
	return nil
}

type ProductData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductData) Reset() {
	*x = ProductData{}
	mi := &file_pkg_api_order_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductData) ProtoMessage() {}

func (x *ProductData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_order_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductData.ProtoReflect.Descriptor instead.
func (*ProductData) Descriptor() ([]byte, []int) {
	return file_pkg_api_order_order_proto_rawDescGZIP(), []int{1}
}

func (x *ProductData) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductData) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type GetOrdersByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersByUserIDRequest) Reset() {
	*x = GetOrdersByUserIDRequest{}
	mi := &file_pkg_api_order_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersByUserIDRequest) ProtoMessage() {}

func (x *GetOrdersByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_order_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersByUserIDRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_order_order_proto_rawDescGZIP(), []int{2}
}

type GetOrdersByUserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*SingleOrder         `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersByUserIDResponse) Reset() {
	*x = GetOrdersByUserIDResponse{}
	mi := &file_pkg_api_order_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersByUserIDResponse) ProtoMessage() {}

func (x *GetOrdersByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_order_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersByUserIDResponse.ProtoReflect.Descriptor instead.
func (*GetOrdersByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_order_order_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrdersByUserIDResponse) GetOrders() []*SingleOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

type GetOrderByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIDRequest) Reset() {
	*x = GetOrderByIDRequest{}
	mi := &file_pkg_api_order_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIDRequest) ProtoMessage() {}

func (x *GetOrderByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_order_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIDRequest.ProtoReflect.Descriptor instead.
func (*GetOrderByIDRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_order_order_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderByIDRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type GetOrderByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *SingleOrder           `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIDResponse) Reset() {
	*x = GetOrderByIDResponse{}
	mi := &file_pkg_api_order_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIDResponse) ProtoMessage() {}

func (x *GetOrderByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_order_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIDResponse.ProtoReflect.Descriptor instead.
func (*GetOrderByIDResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_order_order_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderByIDResponse) GetOrder() *SingleOrder {
	if x != nil {
		return x.Order
	}
	return nil
}

type DeleteOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderRequest) Reset() {
	*x = DeleteOrderRequest{}
	mi := &file_pkg_api_order_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderRequest) ProtoMessage() {}

func (x *DeleteOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_order_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrderRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_order_order_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteOrderRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type DeleteOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderResponse) Reset() {
	*x = DeleteOrderResponse{}
	mi := &file_pkg_api_order_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderResponse) ProtoMessage() {}

func (x *DeleteOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_order_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderResponse.ProtoReflect.Descriptor instead.
func (*DeleteOrderResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_order_order_proto_rawDescGZIP(), []int{7}
}

var File_pkg_api_order_order_proto protoreflect.FileDescriptor

const file_pkg_api_order_order_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/api/order/order.proto\x12\x03api\x1a pkg/google/api/annotations.proto\"d\n" +
	"\vSingleOrder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12,\n" +
	"\bproducts\x18\x03 \x03(\v2\x10.api.ProductDataR\bproducts\"H\n" +
	"\vProductData\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"\x1a\n" +
	"\x18GetOrdersByUserIDRequest\"E\n" +
	"\x19GetOrdersByUserIDResponse\x12(\n" +
	"\x06orders\x18\x01 \x03(\v2\x10.api.SingleOrderR\x06orders\"0\n" +
	"\x13GetOrderByIDRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId\">\n" +
	"\x14GetOrderByIDResponse\x12&\n" +
	"\x05order\x18\x01 \x01(\v2\x10.api.SingleOrderR\x05order\"/\n" +
	"\x12DeleteOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId\"\x15\n" +
	"\x13DeleteOrderResponse2\xbb\x02\n" +
	"\fOrderService\x12f\n" +
	"\x11GetOrdersByUserID\x12\x1d.api.GetOrdersByUserIDRequest\x1a\x1e.api.GetOrdersByUserIDResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/orders\x12_\n" +
	"\vDeleteOrder\x12\x17.api.DeleteOrderRequest\x1a\x18.api.DeleteOrderResponse\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/v1/orders/{order_id}\x12b\n" +
	"\fGetOrderByID\x12\x18.api.GetOrderByIDRequest\x1a\x19.api.GetOrderByIDResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/orders/{order_id}B7Z5github.com/sabirkekw/ecommerce_go/pkg/api/order;orderb\x06proto3"

var (
	file_pkg_api_order_order_proto_rawDescOnce sync.Once
	file_pkg_api_order_order_proto_rawDescData []byte
)

func file_pkg_api_order_order_proto_rawDescGZIP() []byte {
	file_pkg_api_order_order_proto_rawDescOnce.Do(func() {
		file_pkg_api_order_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_order_order_proto_rawDesc), len(file_pkg_api_order_order_proto_rawDesc)))
	})
	return file_pkg_api_order_order_proto_rawDescData
}

var file_pkg_api_order_order_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_api_order_order_proto_goTypes = []any{
	(*SingleOrder)(nil),               // 0: api.SingleOrder
	(*ProductData)(nil),               // 1: api.ProductData
	(*GetOrdersByUserIDRequest)(nil),  // 2: api.GetOrdersByUserIDRequest
	(*GetOrdersByUserIDResponse)(nil), // 3: api.GetOrdersByUserIDResponse
	(*GetOrderByIDRequest)(nil),       // 4: api.GetOrderByIDRequest
	(*GetOrderByIDResponse)(nil),      // 5: api.GetOrderByIDResponse
	(*DeleteOrderRequest)(nil),        // 6: api.DeleteOrderRequest
	(*DeleteOrderResponse)(nil),       // 7: api.DeleteOrderResponse
}
var file_pkg_api_order_order_proto_depIdxs = []int32{
	1, // 0: api.SingleOrder.products:type_name -> api.ProductData
	0, // 1: api.GetOrdersByUserIDResponse.orders:type_name -> api.SingleOrder
	0, // 2: api.GetOrderByIDResponse.order:type_name -> api.SingleOrder
	2, // 3: api.OrderService.GetOrdersByUserID:input_type -> api.GetOrdersByUserIDRequest
	6, // 4: api.OrderService.DeleteOrder:input_type -> api.DeleteOrderRequest
	4, // 5: api.OrderService.GetOrderByID:input_type -> api.GetOrderByIDRequest
	3, // 6: api.OrderService.GetOrdersByUserID:output_type -> api.GetOrdersByUserIDResponse
	7, // 7: api.OrderService.DeleteOrder:output_type -> api.DeleteOrderResponse
	5, // 8: api.OrderService.GetOrderByID:output_type -> api.GetOrderByIDResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_api_order_order_proto_init() }
func file_pkg_api_order_order_proto_init() {
	if File_pkg_api_order_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_order_order_proto_rawDesc), len(file_pkg_api_order_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_order_order_proto_goTypes,
		DependencyIndexes: file_pkg_api_order_order_proto_depIdxs,
		MessageInfos:      file_pkg_api_order_order_proto_msgTypes,
	}.Build()
	File_pkg_api_order_order_proto = out.File
	file_pkg_api_order_order_proto_goTypes = nil
	file_pkg_api_order_order_proto_depIdxs = nil
}
