env: local
postgres:
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: postgres
redis:
  host: localhost
  port: 6379
  database: 0
grpc:
  port: 50054
  timeout: 2s
http:
  port: 8082
  timeout: 2s
jwt_secret: timurlox